[build]
publish = "public"

[functions]
  directory = "lambda"

[[redirects]]
    from = "/api/gallery/*"
    to = "/.netlify/functions/:splat"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
